### ISSUE TITLE
Download and store thumbnails

### ISSUE THREAD

**Issue by wengole** [wengole/comiccollector#22]
on S3

**Comment by wengole** [comment]
somewhere...

**Comment by alexjj** [comment]
Imgur API?

On Mon, Oct 12, 2015 at 05:23, wengole/comiccollector
reply@reply.github.com
wrote:
somewhere...

—
Reply to this email directly or view it on GitHub
[https://github.com/wengole/comiccollector/issues/22#issuecomment-147380487] .[https://github.com/notifications/beacon/AAa6azbt9KiyMeJxPNa3Mrywrboox-keks5o653EgaJpZM4GM0MZ.gif]

**Comment by wengole** [comment]
https://devcenter.heroku.com/articles/cloudinary#using-with-django
