### ISSUE TITLE
Books already in the database shouldn't have an "Add Book" button

### ISSUE THREAD

**Issue by alexjj** [wengole/comiccollector#34]
It fails correctly but the button shouldn't be there.

**Comment by wengole** [comment]
@alexjj I _think_ this has been fixed. When you first search it searches the DB. Clicking "Search Amazon" then does another search and merges the results on ISBN. If there was already a result with an ISBN that was returned form Amazon, it isn't added to the search results.

Can you check?

I can think of an outside case where this would still happen; if you initial DB search doesn't return a result that is in the database (as DB search only covers title) and the Amazon search returns it, then it will appear in the results list. There's no nice fix for this, as we'd have to check every result returned from Amazon is/isn't in the DB, which would be "slow". However this is happening asynchronously, and Amazon only ever returns 10 results at a time.

Thoughts?

**Comment by alexjj** [comment]
You're correct.
